name: CD

on:
    push:
        branches:
            - master
            - beta
        paths:
            - 'packages/**'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install common
              run: yarn install
            - name: Install (ui.styled-components)
              working-directory: ./packages/ui.styled-components
              run: yarn install
            - name: Install peers (ui.styled-components)
              working-directory: ./packages/ui.styled-components
              run: yarn install-peers
            - name: Build (ui.styled-components)
              working-directory: ./packages/ui.styled-components
              run: yarn build
            - name: Install (etc)
              working-directory: ./packages/etc
              run: yarn install
            - name: Install peers (etc)
              working-directory: ./packages/etc
              run: yarn install-peers
            - name: Build (etc)
              working-directory: ./packages/etc
              run: yarn build
            - name: Publish
              run: yarn multi-semantic-release
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.CICD }}
