name: CD

on:
    push:
        branches:
            - master
            - beta
        paths:
            - 'packages/**'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install common
              run: yarn install
            - name: Install peers
              run: yarn run install-peers
            - name: Install (ui)
              working-directory: ./packages/ui
              run: yarn install
            - name: Install peers (ui)
              working-directory: ./packages/ui
              run: yarn install-peers
            - name: Build (ui)
              working-directory: ./packages/ui
              run: yarn build
            - name: Publish
              run: yarn multi-semantic-release
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
