name: CI.etc

on:
    pull_request:
        branches:
            - dev
            - master
        paths:
            - 'packages/etc/**'

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: './packages/etc'

        steps:
            - uses: actions/checkout@v2
            - name: Install
              run: yarn install
            - name: Install peers
              run: yarn install-peers
            - name: Lint
              run: yarn lint
            - name: Test
              run: yarn test
            - name: Build
              run: yarn run build
