name: CI.helpers

on:
    pull_request:
        branches:
            - dev
            - master
        paths:
            - 'packages/helpers/**'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install
              run: yarn install
            - name: Install peers
              run: yarn install-peers

            - name: Lint
              working-directory: ./packages/helpers
              run: yarn lint
            - name: Test
              working-directory: ./packages/helpers
              run: yarn test
            - name: Build
              working-directory: ./packages/helpers
              run: yarn run build
