name: CI

on:
    pull_request:
        branches:
            - dev
            - master
        paths:
            - 'packages/ui.styled-components/**'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install
              run: yarn install
            - name: Install peers
              run: yarn install-peers
            - name: Lint
              run: yarn lint
            - name: Test
              run: yarn test
            - name: Test visual (install)
              working-directory: ./visual
              run: yarn install
            - name: Test visual
              run: yarn test:visual:cicd
            - name: Build
              run: yarn run build
